import React from "react";
import { Minus, Plus, Trash2 } from "lucide-react";
import { useCart } from "../context/cartContext";
import { formatINR } from "../utils/money";

export default function CartPage({ setCurrentPage }) {
  const { items, updateQty, removeItem, subtotal } = useCart();

  if (!items.length) {
    return <section className="mx-auto max-w-4xl px-4 py-20 text-center"><h1 className="text-3xl font-semibold">Your Cart</h1><p className="mt-4 text-[var(--color-muted)]">Your cart is empty.</p><button onClick={() => setCurrentPage("perfumes")} className="mt-8 rounded-lg bg-amber-600 px-6 py-3 font-medium text-white hover:bg-amber-700">Explore Perfumes</button></section>;
  }

  return <section className="mx-auto max-w-6xl px-4 py-12"><h1 className="text-3xl font-semibold">Your Cart</h1><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_340px]"><div className="space-y-4">{items.map(item => <article key={item.product_id} className="flex flex-col gap-4 rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-lg">{item.name}</h2><p className="mt-1 text-amber-700">{formatINR(item.price)}</p></div><div className="flex items-center justify-between gap-5 sm:justify-end"><div className="flex items-center overflow-hidden rounded-lg border border-[var(--color-border)]"><button onClick={() => updateQty(item.product_id, item.qty - 1)} className="p-2.5 hover:bg-[var(--color-surface-muted)]" aria-label={`Decrease ${item.name}`}><Minus className="h-4 w-4" /></button><span className="min-w-9 text-center text-sm font-medium">{item.qty}</span><button onClick={() => updateQty(item.product_id, item.qty + 1)} className="p-2.5 hover:bg-[var(--color-surface-muted)]" aria-label={`Increase ${item.name}`}><Plus className="h-4 w-4" /></button></div><strong className="min-w-20 text-right">{formatINR(item.price * item.qty)}</strong><button onClick={() => removeItem(item.product_id)} className="p-2 text-red-600 hover:text-red-700" aria-label={`Remove ${item.name}`}><Trash2 className="h-5 w-5" /></button></div></article>)}</div><aside className="h-fit rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)] p-6"><h2 className="text-xl font-semibold">Order Summary</h2><div className="mt-5 flex justify-between border-b border-[var(--color-border)] pb-4"><span className="text-[var(--color-muted)]">Subtotal</span><strong>{formatINR(subtotal)}</strong></div><div className="mt-4 flex justify-between text-lg"><span className="font-semibold">Total</span><strong>{formatINR(subtotal)}</strong></div><button onClick={() => setCurrentPage("checkout")} className="mt-6 w-full rounded-lg bg-amber-600 px-5 py-3 font-semibold text-white hover:bg-amber-700">Proceed to Checkout</button><button onClick={() => setCurrentPage("perfumes")} className="mt-3 w-full px-5 py-2.5 text-sm font-medium text-[var(--color-muted)] hover:text-amber-600">Continue Shopping</button></aside></div></section>;
}
